name: Rebase Upstream
on:
  schedule:
  - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  syncmaster:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@main
      with:
        fetch-depth: 0
        ref: master

    - uses: imba-tjd/rebase-upstream-action@master
      with:
        upstream: osm0sis/AnyKernel3
        branch: master

  syncdxt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 0
        ref: payton_dxt

    - uses: imba-tjd/rebase-upstream-action@master
      with:
        upstream: osm0sis/AnyKernel3
        branch: master

  synccybertron:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@main
      with:
        fetch-depth: 0
        ref: payton_cybertron

    - uses: imba-tjd/rebase-upstream-action@master
      with:
        upstream: osm0sis/AnyKernel3
        branch: master
